#!/bin/bash

DIR='/Zanthus/Zeus/pdvJava'
find "$DIR"/ -name *.ZL1 -exec rm -rfv '{}' \;
find "$DIR"/ -name *.NVL -exec rm -rfv '{}' \;
find "$DIR"/ -name *.1VN -exec rm -rfv '{}' \;
find "$DIR"/ -name *.TH00 -exec rm -rfv '{}' \;
find "$DIR"/ -name *.TRA -exec rm -rfv '{}' \;
find "$DIR"/ -name *.PDVPOSTO -exec rm -rfv '{}' \;
find "$DIR"/ -name *.ZZ5 -exec rm -rfv '{}' \;
find "$DIR"/ -name *.dmp -exec rm -rfv '{}' \;
find "$DIR"/ -name *.tmp -exec rm -rfv '{}' \;
find "$DIR"/ -name *.ZMV -exec rm -rfv '{}' \;
find "$DIR"/ -name *~ -exec rm -rfv '{}' \;
find "$DIR"/ -name *.FISCTX -exec rm -rfv '{}' \;
find "$DIR"/ -name *.GZMD -exec rm -rfv '{}' \;
find "$DIR"/ -name *.NV_ -exec rm -rfv '{}' \;

