#!/bin/bash

#	Instalação/Atualização da Extensão do Virtual Box - VERSÃO PARA O REPOSITÓRIO OFICIAL DO UBUNTU

VBoxManage extpack uninstall $(vboxmanage -v | cut -d r -f 2) --force
wget -c "http://download.virtualbox.org/virtualbox/$(vboxmanage -v | cut -d _ -f 1)/Oracle_VM_VirtualBox_Extension_Pack-$(vboxmanage -v | cut -d _ -f 1)-$(vboxmanage -v | cut -d r -f 2).vbox-extpack" -O "/tmp/Oracle_VM_VirtualBox_Extension_Pack-$(vboxmanage -v | cut -d _ -f 1)-$(vboxmanage -v | cut -d r -f 2).vbox-extpack"
sleep 3
sudo VBoxManage extpack install "/tmp/Oracle_VM_VirtualBox_Extension_Pack-$(vboxmanage -v | cut -d _ -f 1)-$(vboxmanage -v | cut -d r -f 2).vbox-extpack" --replace
